[tool.poetry]
name = "cryptoy"
version = "0.1.0"
description = ""
authors = ["steve christensen <adventuresmith.rpg@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
tink = "^1.5.0"
PyNaCl = "^1.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
